name: Cache Demo

on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Prime cache
      id: prime-cache-38f9a8a
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          node_modules
        key: cache-38f9a8a
        
    - name: Show cache result
      run: echo "Cache hit: ${{ steps.prime-cache-38f9a8a.outputs.cache-hit }}"
      
    - name: Install dependencies
      run: npm ci
      
    - name: Run app
      run: node index.js

